name: l2_processing_env
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - scipy
  - pip
  - basemap~=1.2.2
  - basemap-data-hires~=1.2.2
  - pip:
    - pandas~=1.3.3
    - parse~=1.19.0
    - xarray~=0.19.0  # for loading .nc
    - xarray[io]~=0.19.0
    - matplotlib~=3.5.0
    # - rio-tiler~=2.1.3  # for streaming sat data
